name: Go CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Download dependencies
        run: go mod download
      - name: Check formatting
        run: |
          UNFORMATTED=$(gofmt -l $(git ls-files '*.go'))
          if [ -n "$UNFORMATTED" ]; then
            echo "The following files need to be formatted:"
            echo "$UNFORMATTED"
            exit 1
          fi
      - name: Vet
        run: go vet ./...
      - name: Build
        run: go build ./...
      - name: Tidy modules
        run: |
          go mod tidy
          git diff --exit-code
